# Generated by Django 5.2.7 on 2025-10-23 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lapangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('harga_per_jam', models.PositiveIntegerField(default=0)),
                ('gambar', models.ImageField(upload_to='lapangan/')),
                ('fasilitas', models.CharField(blank=True, max_length=200)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentar', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('lapangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.lapangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
