# Generated by Django 5.2.5 on 2025-10-23 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Komunitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('lokasi', models.CharField(max_length=200)),
                ('jenis_olahraga', models.CharField(choices=[('futsal', 'Futsal'), ('basket', 'Basket'), ('badminton', 'Badminton')], max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='komunitas/')),
                ('link_grup', models.URLField(blank=True, max_length=500)),
                ('jumlah_anggota', models.IntegerField(default=0)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Komunitas',
                'ordering': ['-tanggal_dibuat'],
            },
        ),
        migrations.CreateModel(
            name='RequestKomunitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_komunitas', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('jenis_olahraga', models.CharField(max_length=50)),
                ('lokasi_preferensi', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('tanggal_request', models.DateTimeField(auto_now_add=True)),
                ('catatan_admin', models.TextField(blank=True)),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal_request'],
            },
        ),
    ]
