# Generated by Django 5.2.5 on 2025-10-17 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lapangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('jenis', models.CharField(choices=[('futsal', 'Futsal'), ('basket', 'Basket'), ('badminton', 'Badminton')], max_length=50)),
                ('lokasi', models.CharField(max_length=300)),
                ('harga_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deskripsi', models.TextField()),
                ('fasilitas', models.TextField()),
                ('foto_utama', models.ImageField(blank=True, null=True, upload_to='lapangan/')),
                ('is_active', models.BooleanField(default=True)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='KategoriLapangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100)),
                ('lapangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori', to='admin_dashboard.lapangan')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriLapangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='galeri_lapangan/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('lapangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeri', to='admin_dashboard.lapangan')),
            ],
            options={
                'ordering': ['-tanggal_upload'],
            },
        ),
        migrations.CreateModel(
            name='VarianLapangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukuran', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('stock', models.IntegerField(default=1)),
                ('lapangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varian', to='admin_dashboard.lapangan')),
            ],
        ),
        migrations.CreateModel(
            name='WarnaLapangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_warna', models.CharField(max_length=50)),
                ('kode_hex', models.CharField(max_length=7)),
                ('lapangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warna', to='admin_dashboard.lapangan')),
            ],
        ),
    ]
