# Generated by Django 5.2.5 on 2025-10-23 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PENYEWA', 'Penyewa Lapangan'), ('PEMILIK', 'Pemilik Lapangan')], default='PENYEWA', max_length=7)),
                ('nomor_rekening', models.CharField(blank=True, max_length=50, null=True)),
                ('nomor_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
